# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'csci571-news-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for csci571-news-app
  pod 'XLPagerTabStrip', '~>9.0'
  pod 'Alamofire', '~>4.9.1'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'Toast-Swift', '~>4.0.0'
  pod 'SwiftSpinner'
  pod 'Charts'

end
